image: gradle:alpine
stages:
  - build

build:
  stage: build
  script: gradle --build-cache assemble
  artifacts:
    when: always
    paths:
      - build/libs/*.jar

  only:
    - main
    - merge_requests